steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
           'us-central1-docker.pkg.dev/${PROJECT_ID}/cloudfunction-gcp-gov-br/gcp-gov-br',
           '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',
           'us-central1-docker.pkg.dev/${PROJECT_ID}/cloudfunction-gcp-gov-br/gcp-gov-br']
options:
  logging: CLOUD_LOGGING_ONLY
