steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/cloudfunction-gcp-gov-br', '.']
  - images: ['gcr.io/${PROJECT_ID}/cloudfunction-gcp-gov-br']
options:
  logging: CLOUD_LOGGING_ONLY
